spring:
  datasource:
    url: jdbc:mysql://localhost:13306/ai_ann_db?useSSL=false&serverTimezone=UTC
    username: root
    password: Zdy!230003#
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: CQ
  #        namespace: 9b4036eb-bc59-471c-b3a3-a19de58aea55 #dev环境
  #        ephemeral: false # 是否是临时实例


addr-es: #es的服务器ip和端口
  ip: "127.0.0.1"
  port: 9200