server:
  port: 50052
spring:
  application:
    name: extraction-rules-build
  profiles:
    active: dev
mybatis:
  #默认扫描的是启动类所在包路径
  type-aliases-package: com/cqupt/extraction_rules_build/pojo/entity
  mapper-locations: classpath:mapper/*.xml  #sql映射文件位置
  configuration:
    map-underscore-to-camel-case: true